name: continuous prerelease to GitHub

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sign-tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Update translations"
        run: git submodule update --init --recursive --remote

      - name: "Set up node"
        uses: actions/setup-node@v2.4.0

      - name: "Install"
        run: npm install

      - name: "Lint"
        run: npm run lint

      - name: "Set YYYY.MM.DD.minutes version"
        id: version
        run: |
          export VERSION="$(date +%Y.%-m.%-d.)$(echo $(( $(date '+%-H *60 + %-M') )))"
          jq ".version = \"$VERSION\"" src/manifest.json > manifest.json~
          mv manifest.json~ src/manifest.json
          git diff
          echo ::set-output name=version::$(echo $VERSION)

      - name: "Configure add-on for prod site"
        run: npm run config:prod

      - name: "Sign"
        run: ./node_modules/.bin/web-ext sign -s src --channel=unlisted --api-key=${{ secrets.AMO_API_KEY }} --api-secret=${{ secrets.AMO_API_SECRET }}

      - name: "Tag"
        run: |
              git config user.name "GitHub Action: Sign, Tag, Release"
              git config user.email "<>"
              git tag ${{ steps.version.outputs.version }}
              git push origin --tags

      - name: "Make release notes"
        id: release_notes
        run: echo ::set-output name=release_notes::$(git log --no-merges --pretty=format:"%h %s" ${{ steps.version.outputs.version }}^..${{ steps.version.outputs.version }})

      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          files: ./web-ext-artifacts/firefox_relay-${{ steps.version.outputs.version }}-an+fx.xpi
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: ${{ steps.version.outputs.version }}
          body: ${{ steps.release_notes.outputs.release_notes }}
